apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/config.hash: 19f8eb9df37ef760a84c53a81fcc3343
    kubernetes.io/config.mirror: 19f8eb9df37ef760a84c53a81fcc3343
    kubernetes.io/config.seen: "2019-03-29T09:09:31.145511878Z"
    kubernetes.io/config.source: file
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: "2019-03-29T09:12:16Z"
  labels:
    component: etcd
    tier: control-plane
  name: etcd-docker-for-desktop
  namespace: kube-system
  resourceVersion: "34854"
  selfLink: /api/v1/namespaces/kube-system/pods/etcd-docker-for-desktop
  uid: bf1d0cfc-5202-11e9-863b-025000000001
spec:
  containers:
  - command:
    - etcd
    - --trusted-ca-file=/run/config/pki/etcd/ca.crt
    - --peer-cert-file=/run/config/pki/etcd/peer.crt
    - --peer-key-file=/run/config/pki/etcd/peer.key
    - --peer-trusted-ca-file=/run/config/pki/etcd/ca.crt
    - --client-cert-auth=true
    - --peer-client-cert-auth=true
    - --data-dir=/var/lib/etcd
    - --cert-file=/run/config/pki/etcd/server.crt
    - --listen-client-urls=https://127.0.0.1:2379
    - --advertise-client-urls=https://127.0.0.1:2379
    - --key-file=/run/config/pki/etcd/server.key
    image: k8s.gcr.io/etcd-amd64:3.1.12
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -ec
        - ETCDCTL_API=3 etcdctl --endpoints=127.0.0.1:2379 --cacert=/run/config/pki/etcd/ca.crt
          --cert=/run/config/pki/etcd/healthcheck-client.crt --key=/run/config/pki/etcd/healthcheck-client.key
          get foo
      failureThreshold: 8
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 15
    name: etcd
    resources:
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: etcd-data
    - mountPath: /run/config/pki/etcd
      name: etcd-certs
  dnsPolicy: ClusterFirst
  hostNetwork: true
  nodeName: docker-for-desktop
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    operator: Exists
  volumes:
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd-data
  - hostPath:
      path: /run/config/pki/etcd
      type: DirectoryOrCreate
    name: etcd-certs
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-03-30T08:52:57Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-03-30T08:53:00Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-03-30T08:52:57Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://7f02ff5722cf8d7e6d27f0979c442cc27fc1aa1512ef490eb8f9491b7ba81b5f
    image: k8s.gcr.io/etcd-amd64:3.1.12
    imageID: docker-pullable://k8s.gcr.io/etcd-amd64@sha256:68235934469f3bc58917bcf7018bf0d3b72129e6303b0bef28186d96b2259317
    lastState: {}
    name: etcd
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2019-03-30T08:52:59Z"
  hostIP: 192.168.65.3
  phase: Running
  podIP: 192.168.65.3
  qosClass: BestEffort
  startTime: "2019-03-30T08:52:57Z"
