apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
    - image: redis:alpine
      imagePullPolicy: IfNotPresent
      name: redis
      resources: {}
      ports:
        - containerPort: 6379
      volumeMounts:
        - mountPath: /data
          name: redis-data
  volumes:
    - hostPath:
        path: /Users/ken/Documents/gopath/src/play/bitmap/data
        type: DirectoryOrCreate
      name: redis-data
